### ISSUE TITLE
Need markdown table export

### ISSUE THREAD

**Issue by coanor** [yeya24/promlinter#38]
I'm using promlinter to export project's metrics to markdown documents, but it seems the output in plain text like(with `--add-help`):

```
TYPE    NAME              HELP
GAUGE   some_metric       The metrics's help info
```

And I think it's better to show them as table in HTML(create by [mkdocs](https://www.mkdocs.org/) in markdown) with basic markdown table syntax:

| TYPE  |  NAME  |            HELP
|---   |---   |---
| GAUGE  |  `some_metric`    |   The metrics's help info

I think `--md-table` is a good flag. Related to #35.

**Comment by yeya24** [comment]
Closed by #39
